spring.application.name=relayroom
# BACKEND SERVER PORT
server.port=${SERVER_PORT:8080}
# FRONTEND SERVER ORIGIN
allowed.origins=${ALLOWED_ORIGINS:http://localhost:5500}

# Flexibility is assured; SERVER_PORT and ALLOWED_ORIGINS can be assigned environment variables
